global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

#  - job_name: 'node exporter'
#    scrape_interval: 5s
#    static_configs:
#    - targets: ['192.168.12.58:9100']

  - job_name: 'mysqld_exporter'
    static_configs:
    - targets: ['172.50.1.7:9104']
    - targets: ['172.50.1.8:9104']
    - targets: ['172.50.1.9:9104']

