version: '3'
services:
  mysql-server-1:
    container_name: doag2019_mysql1
    env_file:
      - mysql-server.env
    image: mysql/mysql-server:8.0.15
    volumes:
        - ./scripts/db.sql:/docker-entrypoint-initdb.d/init.sql:ro
        - ./utilities:/utilities
    ports:
      - "3301:3306"
      - "33061:33060"
    command: ["mysqld","--server_id=1","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password", "--expire-logs-days=5"]
  mysql-server-2:
    container_name: doag2019_mysql2
    env_file:
      - mysql-server.env
    image: mysql/mysql-server:8.0.15
    volumes:
        - ./scripts/:/scripts/
        - ./utilities:/utilities
    command: ["mysqld","--server_id=2","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log-bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password", "--expire-logs-days=5"]
    ports:
      - "3302:3306"
      - "33062:33060"
  mysql-server-3:
    container_name: doag2019_mysql3
    env_file:
      - mysql-server.env
    image: mysql/mysql-server:8.0.15
    volumes:
        - ./scripts/:/scripts/
        - ./utilities:/utilities
    command: ["mysqld","--server_id=3","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password", "--expire-logs-days=5"]
    ports:
      - "3303:3306"
      - "33063:33060"
  mysql-router:
    container_name: doag2019_router
    env_file:
      - mysql-router.env
    image: mysql/mysql-router:8.0
    ports:
      - "6446:6446"
    depends_on:
      - mysql-server-1
      - mysql-server-2
      - mysql-server-3
#    restart: on-failure
  webdoag:
    image: "rasal2609/nginx:latest"
    ports: 
         - "88:80"
    volumes :
         - $PWD/src/:/var/www/laravel
    restart: always
    container_name: doag2019_nginx
    entrypoint: "/entrypoint.sh"
#    depends_on:
#      - mysql-router
